# fly.toml app configuration file generated for oleg-gusei-cloud on 2023-07-05T13:59:52+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oleg-gusei-cloud"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
